### ISSUE TITLE
[Migrate DB] Fix the right DB migration order

### ISSUE THREAD

**Issue by kompiangg** [nmluci/StellarCoffee#32]
When i want to run the backend, errors appear

```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1005, 'Can\'t create table `stellarCoffee`.`Events` (errno: 150 "Foreign key constraint is incorrectly formed")')   
CREATE TABLE Events (
        id INTEGER NOT NULL AUTO_INCREMENT,
        name TEXT,
        item_name TEXT,
        date_end DATE NOT NULL,
        amount INTEGER NOT NULL,
        amount_type TEXT NOT NULL,
        PRIMARY KEY (id),
        UNIQUE (id),
        UNIQUE (name),
        FOREIGN KEY(item_name) REFERENCES Inventory (name) ON DELETE SET NULL ON UPDATE CASCADE
)
```

I think that error tells us to create the right order for migrating DB. I don't know how to create the right order, sad :(

**Comment by nmluci** [comment]
I think It might be caused by a column changed in some of the table referenced by this table, which ended causing this whole error. My first suggestion would be to wipe all the table of the database first, then reapply the current table structure

**Comment by nmluci** [comment]
After trying simulating the problem in more precise ways, I found out its either mariaDB doesn't play nice with our current database model or out database model itself is the main cause. Well, since its run fine on Postgresql, might considered to also use it in prod
